# Generated by Django 3.2 on 2021-06-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dev_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 30')),
                ('sysops_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 30')),
                ('management_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 40')),
                ('marketing_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 35')),
                ('operative_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 25')),
                ('other_costs_budget', models.PositiveIntegerField()),
                ('total_hours', models.PositiveIntegerField()),
                ('total_budget_resources', models.PositiveIntegerField()),
                ('total_budget_eur', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled'), ('NOT_ACCEPTED', 'Not accepted'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=32)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=256)),
                ('estimated_roi', models.PositiveIntegerField()),
                ('real_roi', models.IntegerField(default=0)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('estimated_dev_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 30')),
                ('estimated_sysops_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 30')),
                ('estimated_management_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 40')),
                ('estimated_marketing_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 35')),
                ('estimated_operative_resources_hours', models.PositiveIntegerField(help_text='Cost €/h: 25')),
                ('estimated_other_cost', models.PositiveIntegerField(help_text='Total costs in €')),
                ('delta_roi', models.FloatField(blank=True, null=True)),
                ('completed_tasks', models.FloatField(blank=True, null=True)),
                ('delayed_tasks', models.IntegerField(blank=True, null=True)),
                ('delayed_tasks_percentage', models.FloatField(blank=True, null=True)),
                ('estimated_total_hours', models.PositiveIntegerField(help_text='€')),
                ('estimated_total_cost', models.PositiveIntegerField(help_text='€')),
                ('estimated_resources_cost', models.PositiveIntegerField(help_text='€')),
                ('total_real_cost', models.PositiveIntegerField(default=0, help_text='Money spent in the project in €')),
                ('is_in_risk', models.BooleanField(default=False)),
                ('is_in_risk_msg', models.CharField(default='', max_length=256)),
                ('is_cancelled_msg', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('projects_total_estimated_costs', models.PositiveIntegerField()),
                ('not_assigned_total_costs', models.PositiveIntegerField()),
                ('projects_dev_resources_hours', models.PositiveIntegerField()),
                ('not_assigned_dev_resources_hours', models.PositiveIntegerField()),
                ('projects_sysops_resources_hours', models.PositiveIntegerField()),
                ('not_assigned_sysops_resources_hours', models.PositiveIntegerField()),
                ('projects_management_resources_hours', models.PositiveIntegerField()),
                ('not_assigned_management_resources_hours', models.PositiveIntegerField()),
                ('projects_marketing_resources_hours', models.PositiveIntegerField()),
                ('not_assigned_marketing_resources_hours', models.PositiveIntegerField()),
                ('projects_operative_resources_hours', models.PositiveIntegerField()),
                ('not_assigned_operative_resources_hours', models.PositiveIntegerField()),
                ('portfolio_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.portfolioconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWalletRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('project_wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_manager_revision', to='control.projectwallet')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cio_revision', to='control.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='PENDING', max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('used_dev_resources_hours', models.PositiveIntegerField(default=0, help_text='Cost €/h: 30')),
                ('used_sysops_resources_hours', models.PositiveIntegerField(default=0, help_text='Cost €/h: 30')),
                ('used_management_resources_hours', models.PositiveIntegerField(default=0, help_text='Cost €/h: 40')),
                ('used_marketing_resources_hours', models.PositiveIntegerField(default=0, help_text='Cost €/h: 35')),
                ('used_operative_resources_hours', models.PositiveIntegerField(default=0, help_text='Cost €/h: 25')),
                ('used_resources_cost', models.PositiveIntegerField(default=0)),
                ('used_other_cost', models.PositiveIntegerField(default=0, help_text='Total costs in €')),
                ('total_real_cost', models.PositiveIntegerField(help_text='Money spent in this task in €')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='control.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='control.projectwallet'),
        ),
        migrations.CreateModel(
            name='PortfolioConfigurationGeneralManagerRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('portfolio_configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_manager_revision', to='control.portfolioconfiguration')),
            ],
        ),
    ]
