# Generated by Django 3.2 on 2021-05-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20210519_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioconfiguration',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='portfolioconfiguration',
            name='dev_resources_hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioconfiguration',
            name='management_resources_hours',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioconfiguration',
            name='marketing_resources_hours',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioconfiguration',
            name='operative_resources_hours',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioconfiguration',
            name='sysops_resources_hours',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioconfiguration',
            name='total_budget_eur',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PortfolioConfigurationGeneralManagerRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget_eur', models.PositiveIntegerField()),
                ('dev_resources_hours', models.PositiveIntegerField()),
                ('sysops_resources_hours', models.PositiveIntegerField()),
                ('management_resources_hours', models.PositiveIntegerField()),
                ('marketing_resources_hours', models.PositiveIntegerField()),
                ('operative_resources_hours', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('portfolio_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_manager_revision', to='control.portfolioconfiguration')),
            ],
        ),
    ]
