# Generated by Django 3.2 on 2021-06-05 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_alter_projectwallet_portfolio_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwallet',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectwallet',
            name='portfolio_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.portfolioconfiguration'),
        ),
    ]
