# Generated by Django 3.2 on 2021-06-08 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20210606_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwallet',
            name='can_add_new_projects',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProjectWalletBlockedNewProejctsRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('project_wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_new_projects_revision', to='control.projectwallet')),
            ],
        ),
    ]
