# Generated by Django 3.2 on 2021-06-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20210608_1909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectWalletBlockedNewProejctsRevision',
            new_name='ProjectWalletBlockedNewProjectsRevision',
        ),
    ]
