# Generated by Django 3.2 on 2021-05-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_portfolioconfiguration_wallet_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectwallet',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectwallet',
            name='portfolio_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.portfolioconfiguration'),
        ),
    ]
