# Generated by Django 3.2 on 2021-06-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_rename_projectwalletblockednewproejctsrevision_projectwalletblockednewprojectsrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwallet',
            name='related_data_can_be_edited',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProjectWalletIsClosedRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('project_wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_closed_revision', to='control.projectwallet')),
            ],
        ),
    ]
