# Generated by Django 3.2 on 2021-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20210523_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwallet',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
