# Generated by Django 3.2 on 2021-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_projectwallet_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectwallet',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='projectwallet',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
