# Generated by Django 3.2 on 2021-06-11 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_projectrevision_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 15, 50, 27, 547308, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
