# Generated by Django 3.2 on 2021-05-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20210523_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioconfiguration',
            name='wallet_closed',
        ),
    ]
