# Generated by Django 3.2 on 2021-06-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_total_hours',
            field=models.PositiveIntegerField(),
        ),
    ]
