# Generated by Django 3.2 on 2021-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_remove_portfolioconfiguration_wallet_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectwallet',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='projectwallet',
            name='required_hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
