# Generated by Django 3.2 on 2021-05-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectwallet',
            name='required_hours',
        ),
        migrations.AddField(
            model_name='project',
            name='required_hours',
            field=models.PositiveIntegerField(default=300),
            preserve_default=False,
        ),
    ]
