# Generated by Django 3.2 on 2021-05-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_auto_20210523_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('DONE', 'Done')], default='PENDING', max_length=32),
        ),
    ]
