# Generated by Django 3.2 on 2021-05-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_auto_20210523_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_roi',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='real_roi',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
