# Generated by Django 3.2 on 2021-05-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_auto_20210523_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delta_roi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
