# Generated by Django 3.2 on 2021-05-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_project_delta_roi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='delta_roi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
