# Generated by Django 3.2 on 2021-06-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_auto_20210602_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='required_hours',
        ),
    ]
