# Generated by Django 3.2 on 2021-06-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_remove_project_required_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioconfiguration',
            name='other_costs_budget',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioconfiguration',
            name='total_budget_resources',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
