# Generated by Django 3.2 on 2021-06-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_auto_20210602_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioconfiguration',
            name='dev_resources_hours',
            field=models.PositiveIntegerField(help_text='Cost €/h: 30'),
        ),
        migrations.AlterField(
            model_name='portfolioconfiguration',
            name='management_resources_hours',
            field=models.PositiveIntegerField(help_text='Cost €/h: 40'),
        ),
        migrations.AlterField(
            model_name='portfolioconfiguration',
            name='marketing_resources_hours',
            field=models.PositiveIntegerField(help_text='Cost €/h: 35'),
        ),
        migrations.AlterField(
            model_name='portfolioconfiguration',
            name='operative_resources_hours',
            field=models.PositiveIntegerField(help_text='Cost €/h: 25'),
        ),
        migrations.AlterField(
            model_name='portfolioconfiguration',
            name='sysops_resources_hours',
            field=models.PositiveIntegerField(help_text='Cost €/h: 30'),
        ),
    ]
