# Generated by Django 3.2 on 2021-06-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_auto_20210602_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_resources_cost',
            field=models.PositiveIntegerField(help_text='€'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_total_cost',
            field=models.PositiveIntegerField(help_text='€'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_total_hours',
            field=models.PositiveIntegerField(help_text='€'),
        ),
    ]
