# Generated by Django 3.2 on 2021-06-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0024_auto_20210602_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_other_cost',
            field=models.PositiveIntegerField(help_text='Total costs in €'),
        ),
    ]
