# Generated by Django 3.2 on 2021-06-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0025_alter_project_estimated_other_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_in_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='total_real_cost',
            field=models.PositiveIntegerField(default=0, help_text='Money spent in the project in €'),
            preserve_default=False,
        ),
    ]
