# Generated by Django 3.2 on 2021-06-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0026_auto_20210602_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField()),
                ('total_delayed_tasks', models.PositiveIntegerField()),
                ('total_delayed_tasks_percentage', models.FloatField()),
                ('total_costs', models.PositiveIntegerField()),
                ('total_revenue', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='total_real_cost',
            field=models.PositiveIntegerField(default=0, help_text='Money spent in this task in €'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='used_dev_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='used_management_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 40'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='used_marketing_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 35'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='used_operative_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 25'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='used_other_cost',
            field=models.PositiveIntegerField(default=0, help_text='Total costs in €'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='used_resources_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='used_sysops_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 30'),
            preserve_default=False,
        ),
    ]
