# Generated by Django 3.2 on 2021-06-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_auto_20210605_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dev_resources_hours',
            new_name='estimated_dev_resources_hours',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='management_resources_hours',
            new_name='estimated_management_resources_hours',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='marketing_resources_hours',
            new_name='estimated_marketing_resources_hours',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='operative_resources_hours',
            new_name='estimated_operative_resources_hours',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sysops_resources_hours',
            new_name='estimated_sysops_resources_hours',
        ),
        migrations.AlterField(
            model_name='portfolioconfigurationgeneralmanagerrevision',
            name='portfolio_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_manager_revision', to='control.portfolioconfiguration'),
        ),
    ]
