# Generated by Django 3.2 on 2021-06-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_auto_20210605_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wallet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.projectwallet'),
        ),
    ]
