# Generated by Django 3.2 on 2021-06-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_alter_project_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='real_roi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_real_cost',
            field=models.PositiveIntegerField(default=0, help_text='Money spent in the project in €'),
        ),
    ]
