# Generated by Django 3.2 on 2021-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0030_auto_20210605_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='used_dev_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 30'),
        ),
    ]
