# Generated by Django 3.2 on 2021-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0031_alter_projectmilestone_used_dev_resources_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='used_management_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 40'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='used_marketing_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 35'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='used_operative_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 25'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='used_sysops_resources_hours',
            field=models.PositiveIntegerField(default=0, help_text='Cost €/h: 30'),
        ),
    ]
