# Generated by Django 3.2 on 2021-06-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0032_auto_20210605_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_in_risk_msg',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='used_other_cost',
            field=models.PositiveIntegerField(default=0, help_text='Total costs in €'),
        ),
    ]
