# Generated by Django 3.2 on 2021-06-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0033_auto_20210605_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_in_risk_msg',
            field=models.CharField(default='Task not in risk', max_length=256),
        ),
    ]
