# Generated by Django 3.2 on 2021-06-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_alter_project_is_in_risk_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_in_risk',
            new_name='is_safe',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_in_risk_msg',
            new_name='is_safe_msg',
        ),
    ]
