# Generated by Django 3.2 on 2021-06-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_auto_20210605_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_cancelled_msg',
            field=models.CharField(default='✅', max_length=256),
        ),
    ]
