# Generated by Django 3.2 on 2021-06-05 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_project_is_cancelled_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_cancelled_msg',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.projectwallet'),
        ),
    ]
