# Generated by Django 3.2 on 2021-06-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0039_projectrevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrevision',
            name='portfolio_configuration',
        ),
        migrations.AddField(
            model_name='projectrevision',
            name='project',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cio_revision', to='control.project'),
            preserve_default=False,
        ),
    ]
