# Generated by Django 3.2 on 2021-06-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0042_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectwallet',
            name='projects_dev_resources_hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectwallet',
            name='projects_management_resources_hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectwallet',
            name='projects_marketing_resources_hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectwallet',
            name='projects_sysops_resources_hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectwallet',
            name='projects_total_estimated_costs',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='control.projectwallet'),
        ),
    ]
